### ISSUE TITLE
Player bloccato con la durata a 0000:05 secondi.

### ISSUE THREAD

**Issue by Xarber** [FoxWorn3365/Cloud#1]
Aprendo un video nel player, questo parte per un po' ma dopo circa 5 secondi il tempo passa a 0000:05 e si blocca il video, nella console invece parte un errore in loop:
```
GET blob:https://c10ud.fcosma.it/bbc655f5-8df8-4971-8990-cc4f768493cb
net: :ERR FILE NOT FOUND
```
BROWSER: Chrome v108

**Comment by FoxWorn3365** [comment]
Risolto con l'ultimo aggiornamento del file `foxplayer.js`
